project:
  type: website

website:
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Exploratory Data Analysis
        href: eda.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Report
        href: report.qmd
      - text: Appendicies
        href: appendix.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

